[package]
name = "comment-yaml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.8.23"
comment = {path = "../comment"}
yaml-rust = "0.4.5"
linked-hash-map = "0.5"
serde = "1.0.133"
